My_Mastermind
simple-lemon/arc-01-my_mastermind pull request #132
Opened 2024-02-21 15:40 UTC by Abuuu2007

2024-02-25 18:26 UTC, simple-lemon requested changes
macros dan foydalanish mumkin emas
int main funksiyasi 10 qatordan qolgan hamma funksiyalar 20 qatordan oshmasligi kerak. 
"ctrl + D" kiritilganda o'yin tugashi kerak edi.
 README.md ni to'g'ri to'ldiring

2024-02-25 18:27 UTC, closed without merging

2024-02-27 13:14 UTC, Abuuu2007 commented
> macros dan foydalanish mumkin emas int main funksiyasi 10 qatordan qolgan hamma funksiyalar 20 qatordan oshmasligi kerak. "ctrl + D" kiritilganda o'yin tugashi kerak edi. README.md ni to'g'ri to'ldiring

manga berilgan shartlar bo'yicha "ctrl + d"dan tashqari xatolarim yo'q.
"Multiline macros are forbidden" - faqatgina ko'p qatorli macroslar taqiqlangan.
qatorlarni limiti haqida bilmagandim, chunki shartda bu haqida yozilmagan.
shunaqada int main 10 qator maximum, boshqa funksiyalar esa har biri 20 qatordan bo'lishi kerakmi yoki umuman 20 qator bo'lishimi?

2024-02-27 14:07 UTC, Abuuu2007 commented
> macros dan foydalanish mumkin emas int main funksiyasi 10 qatordan qolgan hamma funksiyalar 20 qatordan oshmasligi kerak. "ctrl + D" kiritilganda o'yin tugashi kerak edi. README.md ni to'g'ri to'ldiring

yana exitni ishlatish mumkinmi?

2024-02-29 07:34 UTC, simple-lemon commented
yo'q mumkin emas exit