finish
simple-lemon/arc-01-my_mastermind pull request #205
Opened 2024-03-09 11:11 UTC by alimardonb

finish

2024-03-09 19:03 UTC, rinkuo commented
fprintf, strncpy va boshqa funksiyalar ishlatish mumkin emas, bir nechta funksiyalar foydalansa boladi qoidada korsatilgan.
Exit() ishlatish mumkin emas.
Readme nu tug'irlanang va Installation qoshin.

2024-03-13 11:52 UTC, alimardonb commented
finish

2024-03-16 10:13 UTC, alimardonb commented
finish

2024-03-19 02:51 UTC, simple-lemon requested changes
README.md ni to'liqroq to'ldiring.

oyin tog'ri ishlamayabdi.
```
! @simple-lemon ➜ /workspaces/arc-01-my_mastermind (Burxonov_Alimardon) $ ./my_mastermind -c 1234
Will you find the secret code?
Please enter a valid guess
---
Round 0
1233
Wrong input!
---
Round 0
3214
Well-placed pieces: 0
Misplaced pieces: 1
---
Round 1
1234
Well-placed pieces: 1
Misplaced pieces: 0
---
Round 2
```

2024-03-19 02:51 UTC, closed without merging

2024-03-19 05:54 UTC, alimardonb commented
Astrum da misiz

2024-03-19 07:41 UTC, simple-lemon commented
yo'q

2024-03-19 07:47 UTC, alimardonb commented
meni kodimni nimasi xota edi shuni aytib yuboring to'g'rlab tashliman

2024-03-19 08:00 UTC, alimardonb commented
alo aytib yuboring