Ziyoda Yoldoshxojayeva
simple-lemon/arc-01-my_mastermind pull request #216
Opened 2024-03-13 11:55 UTC by YoldoshxojayevaZiyoda

2024-03-18 12:27 UTC, simple-lemon requested changes
```
@simple-lemon ➜ /workspaces/arc-01-my_mastermind (ZIYODA_YO'LDOSHXO'JAYEVA) $ make
make: *** No rule to make target 'my_mastermind.c', needed by 'my_mastermind'.  Stop.
```

kod nimagadur ishlamadi

2024-03-18 12:27 UTC, closed without merging

2024-03-19 10:23 UTC, YoldoshxojayevaZiyoda commented
Assalomu aleymu man kod ishlavotiyu lkn shundan kn tashadm

2024-03-20 04:24 UTC, YoldoshxojayevaZiyoda commented
manda hammasi ishlavoti lkn ishlatb kordm yana
![Uploading Снимок экрана 2024-03-01 161837.png…]()
![Uploading Снимок экрана 2024-03-01 161823.png…]()

2024-03-20 04:24 UTC, YoldoshxojayevaZiyoda commented
manda hammasi ishlavoti lkn ishlatb kordm yana
![Uploading Снимок экрана 2024-03-01 161837.png…]()
![Снимок экрана 2024-03-01 161823](https://github.com/simple-lemon/arc-01-my_mastermind/assets/158573887/ad4ff256-a639-4115-acc4-4f87cc10a666)

2024-03-22 15:13 UTC, YoldoshxojayevaZiyoda commented
Kod hali ham ishlamayaptimi ustoz lkn manda ishlavotide

2024-03-24 02:25 UTC, simple-lemon commented
Dushanba kuni Miranvar Mirabdullayev ga uchrashing.

2024-03-25 05:21 UTC, YoldoshxojayevaZiyoda commented
Assalomu aleykum hop ustoz